version: "3.8"

services:

  guess-the-flag:
    build: .
    image: guess-the-flag
    privileged: true
    restart: always
    environment:
      - JAIL_ENV_FLAG=${FLAG_GUESS_THE_FLAG}
      - JAIL_TIME=600 # 10 minutes
    ports:
      - "5000:5000"